export interface Ingredient {
  category: string;
  group: string;
  description: string;
  name: string;
  id: string;
  image: string;
}

export const ingredients: Ingredient[] = [
  { name:'Ackee',category:'Fruit',group:'Low Fodmap',description:'',id:'253',image:'' },
{ name:'Agave',category:'Condiments, Dips, Sweets, Sweeteners and Spreads',group:'High Fodmap',description:'',id:'111',image:'' },
{ name:'Alfalfa',category:'Vegetables and Legumes',group:'Low Fodmap',description:'',id:'181',image:'' },
{ name:'Almond meal',category:'Cereals, Grains, Biscuits/Cookies, Pasta, Nuts and Cakes',group:'High Fodmap',description:'',id:'86',image:'' },
{ name:'Amaranth flour',category:'Cereals, Grains, Biscuits/Cookies, Pasta, Nuts and Cakes',group:'High Fodmap',description:'',id:'87',image:'' },
{ name:'Apples including pink lady and granny smith',category:'Fruit',group:'High Fodmap',description:'',id:'33',image:'' },
{ name:'Apricots',category:'Fruit',group:'High Fodmap',description:'',id:'34',image:'' },
{ name:'Artichoke',category:'Vegetables and Legumes',group:'High Fodmap',description:'',id:'1',image:'' },
{ name:'Asparagus',category:'Vegetables and Legumes',group:'High Fodmap',description:'',id:'2',image:'' },
{ name:'Avocado',category:'Fruit',group:'High Fodmap',description:'',id:'35',image:'' },
{ name:'Baked beans',category:'Vegetables and Legumes',group:'High Fodmap',description:'',id:'3',image:'' },
{ name:'Bamboo shoots',category:'Vegetables and Legumes',group:'Low Fodmap',description:'',id:'182',image:'' },
{ name:'Bananas, ripe',category:'Fruit',group:'High Fodmap',description:'',id:'36',image:'' },
{ name:'Bananas, unripe',category:'Fruit',group:'Low Fodmap',description:'',id:'254',image:'' },
{ name:'Barley including flour',category:'Cereals, Grains, Biscuits/Cookies, Pasta, Nuts and Cakes',group:'High Fodmap',description:'',id:'88',image:'' },
{ name:'Bean sprouts',category:'Vegetables and Legumes',group:'Low Fodmap',description:'',id:'183',image:'' },
{ name:'Beef',category:'Meats, Poultry and Meat Substitutes',group:'Low Fodmap',description:'',id:'283',image:'' },
{ name:'Beer – if drinking more than one bottle',category:'Drinks and Protein Powders',group:'High Fodmap',description:'',id:'139',image:'' },
{ name:'Beetroot, canned and pickled',category:'Vegetables and Legumes',group:'Low Fodmap',description:'',id:'184',image:'' },
{ name:'Beetroot, fresh',category:'Vegetables and Legumes',group:'High Fodmap',description:'',id:'4',image:'' },
{ name:'Bilberries',category:'Fruit',group:'Low Fodmap',description:'',id:'255',image:'' },
{ name:'Biscuits / cookies including chocolate chip cookies',category:'Wheat containing',group:'High Fodmap',description:'',id:'68',image:'' },
{ name:'Black beans – 1/4 cup / 45g',category:'Vegetables and Legumes',group:'Low Fodmap',description:'',id:'185',image:'' },
{ name:'Black eyed peas',category:'Vegetables and Legumes',group:'High Fodmap',description:'',id:'5',image:'' },
{ name:'Blackberries',category:'Fruit',group:'High Fodmap',description:'',id:'37',image:'' },
{ name:'Blackcurrants',category:'Fruit',group:'High Fodmap',description:'',id:'38',image:'' },
{ name:'Blueberries',category:'Fruit',group:'Low Fodmap',description:'',id:'256',image:'' },
{ name:'Bok choy / pak choi',category:'Vegetables and Legumes',group:'Low Fodmap',description:'',id:'186',image:'' },
{ name:'Boysenberry',category:'Fruit',group:'High Fodmap',description:'',id:'39',image:'' },
{ name:'Bran cereals',category:'Cereals, Grains, Biscuits/Cookies, Pasta, Nuts and Cakes',group:'High Fodmap',description:'',id:'89',image:'' },
{ name:'Bread, wheat – over 1 slice',category:'Wheat containing',group:'High Fodmap',description:'',id:'69',image:'' },
{ name:'Breadcrumbs',category:'Wheat containing',group:'High Fodmap',description:'',id:'70',image:'' },
{ name:'Breadfruit',category:'Fruit',group:'Low Fodmap',description:'',id:'257',image:'' },
{ name:'Broad beans',category:'Vegetables and Legumes',group:'High Fodmap',description:'',id:'6',image:'' },
{ name:'Broccoli, heads only – 3/4 cup',category:'Vegetables and Legumes',group:'Low Fodmap',description:'',id:'188',image:'' },
{ name:'Broccoli, stalks only – 1/2 cup',category:'Vegetables and Legumes',group:'Low Fodmap',description:'',id:'189',image:'' },
{ name:'Broccoli, whole – 1/2 cup',category:'Vegetables and Legumes',group:'Low Fodmap',description:'',id:'187',image:'' },
{ name:'Broccolini, heads only – 1/2 cup',category:'Vegetables and Legumes',group:'Low Fodmap',description:'',id:'191',image:'' },
{ name:'Broccolini, stalks only – 1 cup',category:'Vegetables and Legumes',group:'Low Fodmap',description:'',id:'192',image:'' },
{ name:'Broccolini, whole – 1/2 cup chopped',category:'Vegetables and Legumes',group:'Low Fodmap',description:'',id:'190',image:'' },
{ name:'Brussels sprouts – 2 sprouts',category:'Vegetables and Legumes',group:'Low Fodmap',description:'',id:'193',image:'' },
{ name:'Butter beans',category:'Vegetables and Legumes',group:'High Fodmap',description:'',id:'7',image:'' },
{ name:'Buttermilk',category:'Dairy Foods',group:'High Fodmap',description:'',id:'165',image:'' },
{ name:'Butternut squash – 1/4 cup',category:'Vegetables and Legumes',group:'Low Fodmap',description:'',id:'194',image:'' },
{ name:'Cabbage, common and red up to 1 cup',category:'Vegetables and Legumes',group:'Low Fodmap',description:'',id:'195',image:'' },
{ name:'Cakes',category:'Wheat containing',group:'High Fodmap',description:'',id:'71',image:'' },
{ name:'Callaloo',category:'Vegetables and Legumes',group:'Low Fodmap',description:'',id:'196',image:'' },
{ name:'Canned tuna',category:'Fish and Seafood',group:'Low Fodmap',description:'',id:'294',image:'' },
{ name:'Cantaloupe',category:'Fruit',group:'Low Fodmap',description:'',id:'259',image:'' },
{ name:'Carambola',category:'Fruit',group:'Low Fodmap',description:'',id:'258',image:'' },
{ name:'Carob powder',category:'Cooking ingredients',group:'High Fodmap',description:'',id:'180',image:'' },
{ name:'Carrots',category:'Vegetables and Legumes',group:'Low Fodmap',description:'',id:'197',image:'' },
{ name:'Cashews',category:'Cereals, Grains, Biscuits/Cookies, Pasta, Nuts and Cakes',group:'High Fodmap',description:'',id:'97',image:'' },
{ name:'Cassava',category:'Vegetables and Legumes',group:'High Fodmap',description:'',id:'8',image:'' },
{ name:'Cauliflower',category:'Vegetables and Legumes',group:'High Fodmap',description:'',id:'9',image:'' },
{ name:'Caviar dip',category:'Condiments, Dips, Sweets, Sweeteners and Spreads',group:'High Fodmap',description:'',id:'112',image:'' },
{ name:'Celeriac',category:'Vegetables and Legumes',group:'Low Fodmap',description:'',id:'198',image:'' },
{ name:'Celery – greater than 5cm of stalk',category:'Vegetables and Legumes',group:'High Fodmap',description:'',id:'10',image:'' },
{ name:'Celery – less than 5cm of stalk',category:'Vegetables and Legumes',group:'Low Fodmap',description:'',id:'199',image:'' },
{ name:'Cereal bar, wheat based',category:'Wheat containing',group:'High Fodmap',description:'',id:'72',image:'' },
{ name:'Cheese, cream',category:'Dairy Foods',group:'High Fodmap',description:'',id:'166',image:'' },
{ name:'Cheese, Halmoumi',category:'Dairy Foods',group:'High Fodmap',description:'',id:'167',image:'' },
{ name:'Cheese, ricotta',category:'Dairy Foods',group:'High Fodmap',description:'',id:'168',image:'' },
{ name:'Cherries',category:'Fruit',group:'High Fodmap',description:'',id:'40',image:'' },
{ name:'Chestnut flour',category:'Cereals, Grains, Biscuits/Cookies, Pasta, Nuts and Cakes',group:'High Fodmap',description:'',id:'98',image:'' },
{ name:'Chick peas – 1/4 cup',category:'Vegetables and Legumes',group:'Low Fodmap',description:'',id:'201',image:'' },
{ name:'Chicken',category:'Meats, Poultry and Meat Substitutes',group:'Low Fodmap',description:'',id:'284',image:'' },
{ name:'Chicory leaves',category:'Vegetables and Legumes',group:'Low Fodmap',description:'',id:'200',image:'' },
{ name:'Chilli – if tolerable',category:'Vegetables and Legumes',group:'Low Fodmap',description:'',id:'202',image:'' },
{ name:'Chives',category:'Vegetables and Legumes',group:'Low Fodmap',description:'',id:'203',image:'' },
{ name:'Cho cho – 1/2 cup diced',category:'Vegetables and Legumes',group:'Low Fodmap',description:'',id:'204',image:'' },
{ name:'Choko',category:'Vegetables and Legumes',group:'High Fodmap',description:'',id:'11',image:'' },
{ name:'Chorizo',category:'Meats, Poultry and Meat Substitutes',group:'High Fodmap',description:'',id:'66',image:'' },
{ name:'Choy sum',category:'Vegetables and Legumes',group:'Low Fodmap',description:'',id:'205',image:'' },
{ name:'Clementine',category:'Fruit',group:'Low Fodmap',description:'',id:'261',image:'' },
{ name:'Coconut water',category:'Drinks and Protein Powders',group:'High Fodmap',description:'',id:'140',image:'' },
{ name:'Cod',category:'Fresh fish',group:'Low Fodmap',description:'',id:'295',image:'' },
{ name:'Cold cuts / deli meat / cold meats such as ham and turkey breast',category:'Meats, Poultry and Meat Substitutes',group:'Low Fodmap',description:'',id:'292',image:'' },
{ name:'Collard greens',category:'Vegetables and Legumes',group:'Low Fodmap',description:'',id:'206',image:'' },
{ name:'Cordial, apple and raspberry with 50-100% real juice',category:'Drinks and Protein Powders',group:'High Fodmap',description:'',id:'141',image:'' },
{ name:'Cordial, orange with 25-50% real juice',category:'Drinks and Protein Powders',group:'High Fodmap',description:'',id:'142',image:'' },
{ name:'Corn / sweet corn – if tolerable and only in small amounts – 1/2 cob',category:'Vegetables and Legumes',group:'Low Fodmap',description:'',id:'207',image:'' },
{ name:'Courgette',category:'Vegetables and Legumes',group:'Low Fodmap',description:'',id:'208',image:'' },
{ name:'Cous cous',category:'Cereals, Grains, Biscuits/Cookies, Pasta, Nuts and Cakes',group:'High Fodmap',description:'',id:'99',image:'' },
{ name:'Crab',category:'Seafood',group:'Low Fodmap',description:'',id:'301',image:'' },
{ name:'Cranberry – 1 tbsp',category:'Fruit',group:'Low Fodmap',description:'',id:'260',image:'' },
{ name:'Cream',category:'Dairy Foods',group:'High Fodmap',description:'',id:'169',image:'' },
{ name:'Croissants',category:'Wheat containing',group:'High Fodmap',description:'',id:'73',image:'' },
{ name:'Crumpets',category:'Wheat containing',group:'High Fodmap',description:'',id:'74',image:'' },
{ name:'Cucumber',category:'Vegetables and Legumes',group:'Low Fodmap',description:'',id:'209',image:'' },
{ name:'Currants',category:'Fruit',group:'High Fodmap',description:'',id:'41',image:'' },
{ name:'Custard apple',category:'Fruit',group:'High Fodmap',description:'',id:'42',image:'' },
{ name:'Custard',category:'Dairy Foods',group:'High Fodmap',description:'',id:'170',image:'' },
{ name:'Dates',category:'Fruit',group:'High Fodmap',description:'',id:'43',image:'' },
{ name:'Dragon fruit',category:'Fruit',group:'Low Fodmap',description:'',id:'262',image:'' },
{ name:'Egg noodles',category:'Wheat containing',group:'High Fodmap',description:'',id:'75',image:'' },
{ name:'Eggplant / aubergine',category:'Vegetables and Legumes',group:'Low Fodmap',description:'',id:'210',image:'' },
{ name:'Einkorn flour',category:'Cereals, Grains, Biscuits/Cookies, Pasta, Nuts and Cakes',group:'High Fodmap',description:'',id:'100',image:'' },
{ name:'Falafel',category:'Vegetables and Legumes',group:'High Fodmap',description:'',id:'12',image:'' },
{ name:'Feijoa',category:'Fruit',group:'High Fodmap',description:'',id:'44',image:'' },
{ name:'Fennel',category:'Vegetables and Legumes',group:'Low Fodmap',description:'',id:'211',image:'' },
{ name:'Fermented cabbage e.g. sauerkraut',category:'Vegetables and Legumes',group:'High Fodmap',description:'',id:'13',image:'' },
{ name:'Figs',category:'Fruit',group:'High Fodmap',description:'',id:'45',image:'' },
{ name:'Foie gras',category:'Meats, Poultry and Meat Substitutes',group:'Low Fodmap',description:'',id:'285',image:'' },
{ name:'FOS – fructooligosaccharides',category:'Prebiotic Foods (may be hiding in yoghurts, snack bars etc)',group:'High Fodmap',description:'',id:'136',image:'' },
{ name:'Freekeh',category:'Cereals, Grains, Biscuits/Cookies, Pasta, Nuts and Cakes',group:'High Fodmap',description:'',id:'101',image:'' },
{ name:'Fructose',category:'Condiments, Dips, Sweets, Sweeteners and Spreads',group:'High Fodmap',description:'',id:'113',image:'' },
{ name:'Fruit and herbal teas with apple added',category:'Drinks and Protein Powders',group:'High Fodmap',description:'',id:'143',image:'' },
{ name:'Fruit bar',category:'Condiments, Dips, Sweets, Sweeteners and Spreads',group:'High Fodmap',description:'',id:'114',image:'' },
{ name:'Fruit juices in large quantities',category:'Drinks and Protein Powders',group:'High Fodmap',description:'',id:'144',image:'' },
{ name:'Fruit juices made of apple, pear, mango',category:'Drinks and Protein Powders',group:'High Fodmap',description:'',id:'145',image:'' },
{ name:'Garlic',category:'Vegetables and Legumes',group:'Very high Fodmap',description:'',id:'32',image:'' },
{ name:'Gelato',category:'Dairy Foods',group:'High Fodmap',description:'',id:'171',image:'' },
{ name:'Ginger',category:'Vegetables and Legumes',group:'Low Fodmap',description:'',id:'214',image:'' },
{ name:'Gnocchi',category:'Cereals, Grains, Biscuits/Cookies, Pasta, Nuts and Cakes',group:'High Fodmap',description:'',id:'102',image:'' },
{ name:'Goji berries',category:'Fruit',group:'High Fodmap',description:'',id:'46',image:'' },
{ name:'Granary bread',category:'Bread',group:'High Fodmap',description:'',id:'90',image:'' },
{ name:'Granola bar',category:'Cereals, Grains, Biscuits/Cookies, Pasta, Nuts and Cakes',group:'High Fodmap',description:'',id:'103',image:'' },
{ name:'Grapefruit',category:'Fruit',group:'High Fodmap',description:'',id:'47',image:'' },
{ name:'Grapes',category:'Fruit',group:'Low Fodmap',description:'',id:'264',image:'' },
{ name:'Gravy, if it contains onion',category:'Condiments, Dips, Sweets, Sweeteners and Spreads',group:'High Fodmap',description:'',id:'115',image:'' },
{ name:'Green beans',category:'Vegetables and Legumes',group:'Low Fodmap',description:'',id:'212',image:'' },
{ name:'Green pepper / green bell pepper / green capsicum',category:'Vegetables and Legumes',group:'Low Fodmap',description:'',id:'213',image:'' },
{ name:'Guava, ripe',category:'Fruit',group:'Low Fodmap',description:'',id:'265',image:'' },
{ name:'Guava, unripe',category:'Fruit',group:'High Fodmap',description:'',id:'48',image:'' },
{ name:'Haddock',category:'Fresh fish',group:'Low Fodmap',description:'',id:'296',image:'' },
{ name:'Haricot beans',category:'Vegetables and Legumes',group:'High Fodmap',description:'',id:'14',image:'' },
{ name:'High fructose corn syrup (HFCS)',category:'Condiments, Dips, Sweets, Sweeteners and Spreads',group:'High Fodmap',description:'',id:'116',image:'' },
{ name:'Honey',category:'Condiments, Dips, Sweets, Sweeteners and Spreads',group:'High Fodmap',description:'',id:'118',image:'' },
{ name:'Honeydew and Galia melons',category:'Fruit',group:'Low Fodmap',description:'',id:'266',image:'' },
{ name:'Hummus / houmous',category:'Condiments, Dips, Sweets, Sweeteners and Spreads',group:'High Fodmap',description:'',id:'117',image:'' },
{ name:'Ice cream',category:'Dairy Foods',group:'High Fodmap',description:'',id:'172',image:'' },
{ name:'Inulin',category:'Prebiotic Foods (may be hiding in yoghurts, snack bars etc)',group:'High Fodmap',description:'',id:'137',image:'' },
{ name:'Inulin',category:'Sweeteners and corresponding E number',group:'High Fodmap',description:'',id:'129',image:'' },
{ name:'Isomalt (E953 / 953)',category:'Sweeteners and corresponding E number',group:'High Fodmap',description:'',id:'130',image:'' },
{ name:'Jam, mixed berries',category:'Condiments, Dips, Sweets, Sweeteners and Spreads',group:'High Fodmap',description:'',id:'119',image:'' },
{ name:'Jam, strawberry, if contains HFCS',category:'Condiments, Dips, Sweets, Sweeteners and Spreads',group:'High Fodmap',description:'',id:'120',image:'' },
{ name:'Kale',category:'Vegetables and Legumes',group:'Low Fodmap',description:'',id:'215',image:'' },
{ name:'Kangaroo',category:'Meats, Poultry and Meat Substitutes',group:'Low Fodmap',description:'',id:'286',image:'' },
{ name:'Karela',category:'Vegetables and Legumes',group:'Low Fodmap',description:'',id:'216',image:'' },
{ name:'Kefir',category:'Dairy Foods',group:'High Fodmap',description:'',id:'173',image:'' },
{ name:'Kidney beans',category:'Vegetables and Legumes',group:'High Fodmap',description:'',id:'15',image:'' },
{ name:'Kiwifruit',category:'Fruit',group:'Low Fodmap',description:'',id:'267',image:'' },
{ name:'Kombucha',category:'Drinks and Protein Powders',group:'High Fodmap',description:'',id:'146',image:'' },
{ name:'Lactitol (E966 / 966)',category:'Sweeteners and corresponding E number',group:'High Fodmap',description:'',id:'131',image:'' },
{ name:'Lamb',category:'Meats, Poultry and Meat Substitutes',group:'Low Fodmap',description:'',id:'287',image:'' },
{ name:'Leek bulb',category:'Vegetables and Legumes',group:'High Fodmap',description:'',id:'17',image:'' },
{ name:'Leek leaves',category:'Vegetables and Legumes',group:'Low Fodmap',description:'',id:'217',image:'' },
{ name:'Lemon including lemon juice',category:'Fruit',group:'Low Fodmap',description:'',id:'268',image:'' },
{ name:'Lentils – in small amounts',category:'Vegetables and Legumes',group:'Low Fodmap',description:'',id:'218',image:'' },
{ name:'Lettuce: Butter lettuce',category:'Vegetables and Legumes',group:'Low Fodmap',description:'',id:'219',image:'' },
{ name:'Lettuce: Iceberg lettuce',category:'Vegetables and Legumes',group:'Low Fodmap',description:'',id:'220',image:'' },
{ name:'Lettuce: Radicchio lettuce',category:'Vegetables and Legumes',group:'Low Fodmap',description:'',id:'221',image:'' },
{ name:'Lettuce: Red coral lettuce',category:'Vegetables and Legumes',group:'Low Fodmap',description:'',id:'222',image:'' },
{ name:'Lettuce: Rocket lettuce',category:'Vegetables and Legumes',group:'Low Fodmap',description:'',id:'223',image:'' },
{ name:'Lettuce: Romaine/Cos lettuce',category:'Vegetables and Legumes',group:'Low Fodmap',description:'',id:'224',image:'' },
{ name:'Lima beans',category:'Vegetables and Legumes',group:'High Fodmap',description:'',id:'16',image:'' },
{ name:'Lime including lime juice',category:'Fruit',group:'Low Fodmap',description:'',id:'269',image:'' },
{ name:'Lingonberries',category:'Fruit',group:'Low Fodmap',description:'',id:'263',image:'' },
{ name:'Lobster',category:'Seafood',group:'Low Fodmap',description:'',id:'302',image:'' },
{ name:'Lychee',category:'Fruit',group:'High Fodmap',description:'',id:'49',image:'' },
{ name:'Malted chocolate flavored drink',category:'Drinks and Protein Powders',group:'High Fodmap',description:'',id:'147',image:'' },
{ name:'Maltitol (E965 / 965)',category:'Sweeteners and corresponding E number',group:'High Fodmap',description:'',id:'132',image:'' },
{ name:'Mandarin',category:'Fruit',group:'Low Fodmap',description:'',id:'270',image:'' },
{ name:'Mange Tout',category:'Vegetables and Legumes',group:'High Fodmap',description:'',id:'18',image:'' },
{ name:'Mango',category:'Fruit',group:'High Fodmap',description:'',id:'50',image:'' },
{ name:'Mannitol (E241 / 421)',category:'Sweeteners and corresponding E number',group:'High Fodmap',description:'',id:'133',image:'' },
{ name:'Marrow',category:'Vegetables and Legumes',group:'Low Fodmap',description:'',id:'225',image:'' },
{ name:'Meal replacement drinks containing milk based products e.g. Ensure, Slim Fast',category:'Drinks and Protein Powders',group:'High Fodmap',description:'',id:'148',image:'' },
{ name:'Milk: Cow milk',category:'Dairy Foods',group:'High Fodmap',description:'',id:'174',image:'' },
{ name:'Milk: Evaporated milk',category:'Dairy Foods',group:'High Fodmap',description:'',id:'176',image:'' },
{ name:'Milk: Goat milk',category:'Dairy Foods',group:'High Fodmap',description:'',id:'175',image:'' },
{ name:'Milk: Sheep’s milk',category:'Dairy Foods',group:'High Fodmap',description:'',id:'177',image:'' },
{ name:'Mixed vegetables',category:'Vegetables and Legumes',group:'High Fodmap',description:'',id:'19',image:'' },
{ name:'Molasses',category:'Condiments, Dips, Sweets, Sweeteners and Spreads',group:'High Fodmap',description:'',id:'121',image:'' },
{ name:'Muesli bar',category:'Cereals, Grains, Biscuits/Cookies, Pasta, Nuts and Cakes',group:'High Fodmap',description:'',id:'105',image:'' },
{ name:'Muesli cereal',category:'Cereals, Grains, Biscuits/Cookies, Pasta, Nuts and Cakes',group:'High Fodmap',description:'',id:'104',image:'' },
{ name:'Muffins',category:'Wheat containing',group:'High Fodmap',description:'',id:'76',image:'' },
{ name:'Multigrain bread',category:'Bread',group:'High Fodmap',description:'',id:'91',image:'' },
{ name:'Mung beans',category:'Vegetables and Legumes',group:'High Fodmap',description:'',id:'20',image:'' },
{ name:'Mushrooms',category:'Vegetables and Legumes',group:'High Fodmap',description:'',id:'21',image:'' },
{ name:'Mussels',category:'Seafood',group:'Low Fodmap',description:'',id:'303',image:'' },
{ name:'Naan',category:'Bread',group:'High Fodmap',description:'',id:'92',image:'' },
{ name:'Nectarines',category:'Fruit',group:'High Fodmap',description:'',id:'51',image:'' },
{ name:'Oatmeal bread',category:'Bread',group:'High Fodmap',description:'',id:'93',image:'' },
{ name:'Okra',category:'Vegetables and Legumes',group:'Low Fodmap',description:'',id:'226',image:'' },
{ name:'Oligofructose',category:'Prebiotic Foods (may be hiding in yoghurts, snack bars etc)',group:'High Fodmap',description:'',id:'138',image:'' },
{ name:'Olives',category:'Vegetables and Legumes',group:'Low Fodmap',description:'',id:'227',image:'' },
{ name:'Onion',category:'Vegetables and Legumes',group:'Very high Fodmap',description:'',id:'31',image:'' },
{ name:'Orange juice in quantities over 100ml',category:'Drinks and Protein Powders',group:'High Fodmap',description:'',id:'149',image:'' },
{ name:'Orange',category:'Fruit',group:'Low Fodmap',description:'',id:'271',image:'' },
{ name:'Oysters',category:'Seafood',group:'Low Fodmap',description:'',id:'304',image:'' },
{ name:'Papaya',category:'Fruit',group:'Low Fodmap',description:'',id:'274',image:'' },
{ name:'Parsnip',category:'Vegetables and Legumes',group:'Low Fodmap',description:'',id:'228',image:'' },
{ name:'Passion fruit',category:'Fruit',group:'Low Fodmap',description:'',id:'272',image:'' },
{ name:'Pasta, wheat over 1/2 cup cooked',category:'Wheat containing',group:'High Fodmap',description:'',id:'78',image:'' },
{ name:'Pastries',category:'Wheat containing',group:'High Fodmap',description:'',id:'77',image:'' },
{ name:'Paw paw, dried',category:'Fruit',group:'High Fodmap',description:'',id:'52',image:'' },
{ name:'Paw paw',category:'Fruit',group:'Low Fodmap',description:'',id:'273',image:'' },
{ name:'Peaches',category:'Fruit',group:'High Fodmap',description:'',id:'53',image:'' },
{ name:'Pears',category:'Fruit',group:'High Fodmap',description:'',id:'54',image:'' },
{ name:'Peas, snow – 5 pods',category:'Vegetables and Legumes',group:'Low Fodmap',description:'',id:'229',image:'' },
{ name:'Peas, sugar snap',category:'Vegetables and Legumes',group:'High Fodmap',description:'',id:'22',image:'' },
{ name:'Persimmon',category:'Fruit',group:'High Fodmap',description:'',id:'55',image:'' },
{ name:'Pesto sauce',category:'Condiments, Dips, Sweets, Sweeteners and Spreads',group:'High Fodmap',description:'',id:'122',image:'' },
{ name:'Pickled gherkins',category:'Vegetables and Legumes',group:'Low Fodmap',description:'',id:'230',image:'' },
{ name:'Pickled onions, large',category:'Vegetables and Legumes',group:'Low Fodmap',description:'',id:'231',image:'' },
{ name:'Pickled vegetables',category:'Vegetables and Legumes',group:'High Fodmap',description:'',id:'23',image:'' },
{ name:'Pineapple, dried',category:'Fruit',group:'High Fodmap',description:'',id:'56',image:'' },
{ name:'Pineapple',category:'Fruit',group:'Low Fodmap',description:'',id:'275',image:'' },
{ name:'Pistachios',category:'Cereals, Grains, Biscuits/Cookies, Pasta, Nuts and Cakes',group:'High Fodmap',description:'',id:'106',image:'' },
{ name:'Plaice',category:'Fresh fish',group:'Low Fodmap',description:'',id:'297',image:'' },
{ name:'Plantain, peeled',category:'Fruit',group:'Low Fodmap',description:'',id:'276',image:'' },
{ name:'Plums',category:'Fruit',group:'High Fodmap',description:'',id:'57',image:'' },
{ name:'Pomegranate',category:'Fruit',group:'High Fodmap',description:'',id:'58',image:'' },
{ name:'Pork',category:'Meats, Poultry and Meat Substitutes',group:'Low Fodmap',description:'',id:'288',image:'' },
{ name:'Potato',category:'Vegetables and Legumes',group:'Low Fodmap',description:'',id:'232',image:'' },
{ name:'Prawns',category:'Seafood',group:'Low Fodmap',description:'',id:'305',image:'' },
{ name:'Prickly pear / nopales',category:'Fruit',group:'Low Fodmap',description:'',id:'277',image:'' },
{ name:'Processed meat – check ingredients',category:'Meats, Poultry and Meat Substitutes',group:'Low Fodmap',description:'',id:'293',image:'' },
{ name:'Prosciutto',category:'Meats, Poultry and Meat Substitutes',group:'Low Fodmap',description:'',id:'289',image:'' },
{ name:'Prunes',category:'Fruit',group:'High Fodmap',description:'',id:'59',image:'' },
{ name:'Pumpernickel bread',category:'Bread',group:'High Fodmap',description:'',id:'94',image:'' },
{ name:'Pumpkin, canned – 1/4 cup, 2.2 oz',category:'Vegetables and Legumes',group:'Low Fodmap',description:'',id:'234',image:'' },
{ name:'Pumpkin',category:'Vegetables and Legumes',group:'Low Fodmap',description:'',id:'233',image:'' },
{ name:'Quince paste',category:'Condiments, Dips, Sweets, Sweeteners and Spreads',group:'High Fodmap',description:'',id:'123',image:'' },
{ name:'Quinoa milk',category:'Drinks and Protein Powders',group:'High Fodmap',description:'',id:'150',image:'' },
{ name:'Quorn, mince',category:'Meats, Poultry and Meat Substitutes',group:'Low Fodmap',description:'',id:'290',image:'' },
{ name:'Radish',category:'Vegetables and Legumes',group:'Low Fodmap',description:'',id:'235',image:'' },
{ name:'Raisins',category:'Fruit',group:'High Fodmap',description:'',id:'60',image:'' },
{ name:'Raspberry',category:'Fruit',group:'Low Fodmap',description:'',id:'278',image:'' },
{ name:'Red kidney beans',category:'Vegetables and Legumes',group:'High Fodmap',description:'',id:'24',image:'' },
{ name:'Red peppers / red bell pepper / red capsicum',category:'Vegetables and Legumes',group:'Low Fodmap',description:'',id:'236',image:'' },
{ name:'Relish / vegetable pickle',category:'Condiments, Dips, Sweets, Sweeteners and Spreads',group:'High Fodmap',description:'',id:'124',image:'' },
{ name:'Rhubarb',category:'Fruit',group:'Low Fodmap',description:'',id:'279',image:'' },
{ name:'Roti',category:'Bread',group:'High Fodmap',description:'',id:'95',image:'' },
{ name:'Rum',category:'Drinks and Protein Powders',group:'High Fodmap',description:'',id:'151',image:'' },
{ name:'Rye crispbread',category:'Cereals, Grains, Biscuits/Cookies, Pasta, Nuts and Cakes',group:'High Fodmap',description:'',id:'108',image:'' },
{ name:'Rye',category:'Cereals, Grains, Biscuits/Cookies, Pasta, Nuts and Cakes',group:'High Fodmap',description:'',id:'107',image:'' },
{ name:'Salmon',category:'Fresh fish',group:'Low Fodmap',description:'',id:'298',image:'' },
{ name:'Sausages',category:'Meats, Poultry and Meat Substitutes',group:'High Fodmap',description:'',id:'67',image:'' },
{ name:'Savoy Cabbage',category:'Vegetables and Legumes',group:'High Fodmap',description:'',id:'25',image:'' },
{ name:'Scallions / spring onions (bulb / white part)',category:'Vegetables and Legumes',group:'High Fodmap',description:'',id:'28',image:'' },
{ name:'Scallions / spring onions (green part)',category:'Vegetables and Legumes',group:'Low Fodmap',description:'',id:'237',image:'' },
{ name:'Sea buckthorns',category:'Fruit',group:'High Fodmap',description:'',id:'61',image:'' },
{ name:'Seaweed / nori',category:'Vegetables and Legumes',group:'Low Fodmap',description:'',id:'238',image:'' },
{ name:'Semolina',category:'Cereals, Grains, Biscuits/Cookies, Pasta, Nuts and Cakes',group:'High Fodmap',description:'',id:'109',image:'' },
{ name:'Shallots',category:'Vegetables and Legumes',group:'High Fodmap',description:'',id:'29',image:'' },
{ name:'Shrimp',category:'Seafood',group:'Low Fodmap',description:'',id:'306',image:'' },
{ name:'Silverbeet / chard',category:'Vegetables and Legumes',group:'Low Fodmap',description:'',id:'239',image:'' },
{ name:'Sodas containing High Fructose Corn Syrup (HFCS)',category:'Drinks and Protein Powders',group:'High Fodmap',description:'',id:'152',image:'' },
{ name:'Sorbitol (E420 / 420)',category:'Sweeteners and corresponding E number',group:'High Fodmap',description:'',id:'134',image:'' },
{ name:'Sour cream',category:'Dairy Foods',group:'High Fodmap',description:'',id:'178',image:'' },
{ name:'Sourdough with kamut',category:'Bread',group:'High Fodmap',description:'',id:'96',image:'' },
{ name:'Soy beans / soya beans',category:'Vegetables and Legumes',group:'High Fodmap',description:'',id:'26',image:'' },
{ name:'Soy milk made with soy beans – commonly found in USA',category:'Drinks and Protein Powders',group:'High Fodmap',description:'',id:'153',image:'' },
{ name:'Spaghetti squash',category:'Vegetables and Legumes',group:'Low Fodmap',description:'',id:'240',image:'' },
{ name:'Spelt flour',category:'Cereals, Grains, Biscuits/Cookies, Pasta, Nuts and Cakes',group:'High Fodmap',description:'',id:'110',image:'' },
{ name:'Spinach, baby',category:'Vegetables and Legumes',group:'Low Fodmap',description:'',id:'241',image:'' },
{ name:'Split peas',category:'Vegetables and Legumes',group:'High Fodmap',description:'',id:'27',image:'' },
{ name:'Sports drinks',category:'Drinks and Protein Powders',group:'High Fodmap',description:'',id:'154',image:'' },
{ name:'Squash',category:'Vegetables and Legumes',group:'Low Fodmap',description:'',id:'242',image:'' },
{ name:'Stock cubes',category:'Condiments, Dips, Sweets, Sweeteners and Spreads',group:'High Fodmap',description:'',id:'125',image:'' },
{ name:'Strawberry',category:'Fruit',group:'Low Fodmap',description:'',id:'280',image:'' },
{ name:'Sugar free sweets containing polyols – usually ending in -ol or isomalt',category:'Condiments, Dips, Sweets, Sweeteners and Spreads',group:'High Fodmap',description:'',id:'126',image:'' },
{ name:'Sultanas',category:'Fruit',group:'High Fodmap',description:'',id:'62',image:'' },
{ name:'Sun-dried tomatoes – 4 pieces',category:'Vegetables and Legumes',group:'Low Fodmap',description:'',id:'243',image:'' },
{ name:'Swede',category:'Vegetables and Legumes',group:'Low Fodmap',description:'',id:'244',image:'' },
{ name:'Sweet potato – 1/2 cup',category:'Vegetables and Legumes',group:'Low Fodmap',description:'',id:'246',image:'' },
{ name:'Swiss chard',category:'Vegetables and Legumes',group:'Low Fodmap',description:'',id:'245',image:'' },
{ name:'Tahini paste',category:'Condiments, Dips, Sweets, Sweeteners and Spreads',group:'High Fodmap',description:'',id:'127',image:'' },
{ name:'Tamarillo',category:'Fruit',group:'High Fodmap',description:'',id:'63',image:'' },
{ name:'Tamarind',category:'Fruit',group:'Low Fodmap',description:'',id:'281',image:'' },
{ name:'Tangelo',category:'Fruit',group:'Low Fodmap',description:'',id:'282',image:'' },
{ name:'Taro',category:'Vegetables and Legumes',group:'High Fodmap',description:'',id:'30',image:'' },
{ name:'Tea: Black tea with added soy milk',category:'Drinks and Protein Powders',group:'High Fodmap',description:'',id:'155',image:'' },
{ name:'Tea: Chai tea, strong',category:'Drinks and Protein Powders',group:'High Fodmap',description:'',id:'156',image:'' },
{ name:'Tea: Chamomile tea',category:'Drinks and Protein Powders',group:'High Fodmap',description:'',id:'159',image:'' },
{ name:'Tea: Dandelion tea, strong',category:'Drinks and Protein Powders',group:'High Fodmap',description:'',id:'157',image:'' },
{ name:'Tea: Fennel tea',category:'Drinks and Protein Powders',group:'High Fodmap',description:'',id:'158',image:'' },
{ name:'Tea: Herbal tea, strong',category:'Drinks and Protein Powders',group:'High Fodmap',description:'',id:'160',image:'' },
{ name:'Tea: Oolong tea',category:'Drinks and Protein Powders',group:'High Fodmap',description:'',id:'161',image:'' },
{ name:'Tinned fruit in apple / pear juice',category:'Fruit',group:'High Fodmap',description:'',id:'64',image:'' },
{ name:'Tomatillos – canned',category:'Vegetables and Legumes',group:'Low Fodmap',description:'',id:'248',image:'' },
{ name:'Tomato – canned, cherry, common, roma',category:'Vegetables and Legumes',group:'Low Fodmap',description:'',id:'247',image:'' },
{ name:'Trout',category:'Fresh fish',group:'Low Fodmap',description:'',id:'299',image:'' },
{ name:'Tuna',category:'Fresh fish',group:'Low Fodmap',description:'',id:'300',image:'' },
{ name:'Turkey',category:'Meats, Poultry and Meat Substitutes',group:'Low Fodmap',description:'',id:'291',image:'' },
{ name:'Turnip',category:'Vegetables and Legumes',group:'Low Fodmap',description:'',id:'249',image:'' },
{ name:'Tzatziki dip',category:'Condiments, Dips, Sweets, Sweeteners and Spreads',group:'High Fodmap',description:'',id:'128',image:'' },
{ name:'Udon noodles',category:'Wheat containing',group:'High Fodmap',description:'',id:'79',image:'' },
{ name:'Water chestnuts',category:'Vegetables and Legumes',group:'Low Fodmap',description:'',id:'250',image:'' },
{ name:'Watermelon',category:'Fruit',group:'High Fodmap',description:'',id:'65',image:'' },
{ name:'Wheat bran',category:'Wheat containing',group:'High Fodmap',description:'',id:'80',image:'' },
{ name:'Wheat cereals',category:'Wheat containing',group:'High Fodmap',description:'',id:'81',image:'' },
{ name:'Wheat flour',category:'Wheat containing',group:'High Fodmap',description:'',id:'82',image:'' },
{ name:'Wheat germ',category:'Wheat containing',group:'High Fodmap',description:'',id:'83',image:'' },
{ name:'Wheat noodles',category:'Wheat containing',group:'High Fodmap',description:'',id:'84',image:'' },
{ name:'Wheat rolls',category:'Wheat containing',group:'High Fodmap',description:'',id:'85',image:'' },
{ name:'Whey protein, concentrate unless lactose free',category:'Drinks and Protein Powders',group:'High Fodmap',description:'',id:'163',image:'' },
{ name:'Whey protein, hydrolyzed unless lactose free',category:'Drinks and Protein Powders',group:'High Fodmap',description:'',id:'164',image:'' },
{ name:'Wine – if drinking more than one glass',category:'Drinks and Protein Powders',group:'High Fodmap',description:'',id:'162',image:'' },
{ name:'Xylitol (E967 / 967)',category:'Sweeteners and corresponding E number',group:'High Fodmap',description:'',id:'135',image:'' },
{ name:'Yam',category:'Vegetables and Legumes',group:'Low Fodmap',description:'',id:'251',image:'' },
{ name:'Yoghurt',category:'Dairy Foods',group:'High Fodmap',description:'',id:'179',image:'' },
{ name:'Zucchini',category:'Vegetables and Legumes',group:'Low Fodmap',description:'',id:'252',image:'' },
];
